services:
  postgres:
    image: postgres:16-alpine
    container_name: worksphere-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: worksphere
      POSTGRES_PASSWORD: worksphere_pass
      POSTGRES_DB: inout
    ports:
      - "5432:5432"
    volumes:
      - worksphere_pgdata:/var/lib/postgresql/data
volumes:
  worksphere_pgdata:
